/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabchamdospoo;

import java.awt.event.ActionEvent;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


    


public class attChamadosView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(attChamadosView.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public attChamadosView() {
        initComponents();
    }
    
    private void atualizarTabela(String termo){
        attChamadosController ctrl = new attChamadosController();
        ArrayList<attChamadosModel> lChamados =  ctrl.pesquisar(termo);
        DefaultTableModel modelo = (DefaultTableModel) jTChamados.getModel();
        modelo.setNumRows(0);

        for (attChamadosModel chamado : lChamados) {
            Object[] linha = {
            chamado.getUsuario(),
            chamado.getTicket(),
            chamado.getSetor(),
            chamado.getProblema(),
            chamado.getCusto(),
            chamado.isResolvido() ? "Sim" : "Não"
            };
            modelo.addRow(linha);
            
        }
        
    }

    private void atualizarCampos(){
        jTxtUsuario.setText("");
        jTxtUsuario.requestFocusInWindow();
        jTxtTicket.setText("");
        jTxtSetor.setText("");
        jTxtProblema.setText("");
        jTxtCusto.setText("");
        jCbxResolvido.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtPesquisa = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtTicket = new javax.swing.JTextField();
        jTxtSetor = new javax.swing.JTextField();
        jTxtProblema = new javax.swing.JTextField();
        jCbxResolvido = new javax.swing.JComboBox<>();
        jTxtCusto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTChamados = new javax.swing.JTable();
        jBSalvar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pesquisar");

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(this::jBPesquisarActionPerformed);

        jBNovo.setText("Novo");
        jBNovo.addActionListener(this::jBNovoActionPerformed);

        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Setor*");

        jCbxResolvido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não", " " }));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ticket *");

        jLabel4.setText("Resolvido");

        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Problema*");

        jLabel6.setText("Custo");

        jTChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Ticket", "Setor", "Problema", "Custo", "Ativo"
            }
        ));
        jTChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTChamadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTChamados);

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(this::jBSalvarActionPerformed);

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(this::jBExcluirActionPerformed);

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(this::jBAtualizarActionPerformed);

        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Usuario*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jTxtUsuario))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(jBNovo)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(51, 51, 51))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxtCusto)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jCbxResolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16)
                                        .addComponent(jBSalvar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jTxtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 73, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(252, 252, 252))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar)
                    .addComponent(jBNovo))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalvar)
                    .addComponent(jTxtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbxResolvido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBAtualizar)))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        String usuario = jTxtUsuario.getText();
        String ticket = jTxtTicket.getText();
        String setor = jTxtSetor.getText();
        String problema = jTxtProblema.getText();
        double custo = jTxtCusto.getText().isEmpty() ? 0 : Double.parseDouble(jTxtCusto.getText());
        boolean resolvido = jCbxResolvido.getSelectedItem().equals("Sim");

        if(usuario.isEmpty() || ticket.isEmpty() || setor.isEmpty() || problema.isEmpty()){
          JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
            return;
        }

        attChamadosModel chamado = new attChamadosModel(usuario, ticket, setor, problema, custo, resolvido);
        attChamadosController ctrl = new attChamadosController();
        ctrl.salvar(chamado);
        atualizarCampos();
        atualizarTabela("");
          
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        int linhaSelecionada = jTChamados.getSelectedRow();
        if(linhaSelecionada >=0){
            String usuario = jTxtUsuario.getText();
            String ticket = jTxtTicket.getText();
            String setor = jTxtSetor.getText();
            String problema = jTxtProblema.getText();
            double custo = jTxtCusto.getText().isEmpty() ? 0 : Double.parseDouble(jTxtCusto.getText());
            boolean resolvido = jCbxResolvido.getSelectedItem().equals("Sim");

            if(usuario.isEmpty() || ticket.isEmpty() || setor.isEmpty() || problema.isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
                return;
            }

            attChamadosModel chamadoAtualizado = new attChamadosModel(usuario, ticket, setor, problema, custo, resolvido);
            attChamadosController ctrl = new attChamadosController();
            ctrl.atualizar(linhaSelecionada, chamadoAtualizado);
            atualizarCampos();
            atualizarTabela("");

        } 
        
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linhaSelecionada = jTChamados.getSelectedRow();
        if(linhaSelecionada >=0){
            attChamadosController ctrl = new attChamadosController();
            ctrl.excluir(linhaSelecionada);
            atualizarCampos();
            atualizarTabela("");
        }else {
            JOptionPane.showMessageDialog(null,"");
        }
        
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        String termo = jTxtPesquisa.getText().trim();
        atualizarTabela(termo);
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        atualizarCampos();
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jTChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTChamadosMouseClicked
         int linhaSelecionada = jTChamados.getSelectedRow();
        if(linhaSelecionada >=0){
            attChamadosController ctrl = new attChamadosController();
            
            attChamadosModel chamadoSelecionado = ctrl.listar().get(linhaSelecionada);jTxtUsuario.setText("");
            jTxtUsuario.setText(chamadoSelecionado.getUsuario());
            jTxtTicket.setText(chamadoSelecionado.getTicket());
            jTxtSetor.setText(chamadoSelecionado.getSetor());
            jTxtProblema.setText(chamadoSelecionado.getProblema());
            if(chamadoSelecionado.isResolvido()){
                jCbxResolvido.setSelectedItem("Sim");
            } else {
                jCbxResolvido.setSelectedItem("Não");
            }
            jTxtCusto.setText(String.valueOf(chamadoSelecionado.getCusto()));
            
            
            
            
        }else {
            JOptionPane.showMessageDialog(null,"");
        }
    }//GEN-LAST:event_jTChamadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new attChamadosView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<String> jCbxResolvido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTChamados;
    private javax.swing.JTextField jTxtCusto;
    private javax.swing.JTextField jTxtPesquisa;
    private javax.swing.JTextField jTxtProblema;
    private javax.swing.JTextField jTxtSetor;
    private javax.swing.JTextField jTxtTicket;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables

    private void jTxtUsuarioActionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
